# Generated by Django 4.1 on 2022-09-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0002_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
